### ISSUE TITLE
Make Bower package

### ISSUE THREAD

**Issue by phil-hudson** [szrnka-peter/ngAdsense#2]
Would this be possible please?

**Comment by peter-szrnka** [comment]
Hi Phil,

Sure, I'll try to do it on this week.

**Comment by phil-hudson** [comment]
awesome! also apologies, I meant Bower, not NPM :)

**Comment by peter-szrnka** [comment]
To tell the truth, I never did a Bower package before, because I'm a Java EE developer, but I think & hope it works :) Bower module name is "ngAdsense"

**Comment by phil-hudson** [comment]
woo awesome, thank you!
